FROM redhat/ubi10:10.0
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh
RUN source /tmp/install_deps.sh && install_deps_el10
ADD . /opt/aql
WORKDIR /opt/aql
ENTRYPOINT ["/opt/aql/.github/docker/entrypoint.sh"]
CMD ["-b"]
