name: "Draft Release"

on:
  push:
    tags:
      - "*"

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    name: Draft Release
    steps:
      - uses: actions/checkout@v3
      # finally create the release and upload artifacts
      - name: Upload Artifacts to Release Draft
        uses: "softprops/action-gh-release@v1"
        with:
          draft: true
          generate_release_notes: true
