name: Mac Build CI

on:
  repository_dispatch:
    types: mac-build
  push:
    branches: [actionsHub, master, test-ready, TOOLS-1994-build-mac-in-action]
  pull_request:
    branches: [actionsHub]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download C Client Deps
        run: |
          brew install automake
      - name: Cache C Client
        uses: actions/cache@v3
        env:
          cache-name: cache-c-client
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            c-client/target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('c-client') }}
      - name: Cache Jansson
        uses: actions/cache@v3
        env:
          cache-name: cache-jansson
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            jansson/src/.libs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('jansson') }}
      - name: Build aql
        run: |
          make
      - uses: actions/upload-artifact@v3
        with:
          name: aql
          path: target/Darwin-x86_64/bin/aql
      - name: Sanity Test tools
        run: |
          target/Darwin-x86_64/bin/aql -e "info" 2>&1 | grep "Failed to connect"