name: Mac Build CI

on:
  repository_dispatch:
    types: mac-build
  push:
    branches: [actionsHub, master, test-ready, TOOLS-1994-build-mac-in-action]
  pull_request:
    branches: [actionsHub]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download C Client Deps
        run: |
          brew install automake
      - name: Cache C Client
        id: cache-aws-sdk-cpp
        uses: actions/cache@v2
        env:
          cache-name: aws-sdk-cpp
        with:
          path: aws-sdk-cpp
          key: aws-sdk-cpp-v2-${{ runner.os }}
      - name: Build aql
        run: |
          make
      - name: Sanity Test tools
        run: |
          target/Darwin-x86_64/bin/aql -e "info" 2>&1 | grep "Not able to connect"
      - uses: actions/upload-artifact@v3
        with:
          name: aql
          path: target/Darwin-x86_64/bin/aql